{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your project is using "},{"type":"codeVoice","code":"RxSwift"},{"type":"text","text":", and the data model parsing framework you use is "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", which is a commonly used responsive framework and data parsing framework in iOS development, then it is very suitable to use the "},{"type":"codeVoice","code":"SYMoyaRxObjectMapper"},{"type":"text","text":" Framework."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/symoyarxobjectmapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/symoyarxobjectmapper"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Supports "},{"type":"codeVoice","code":"RxSwift"},{"type":"text","text":" responsive framework and uses "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":" to parse data."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SYMoyaRxObjectMapper","title":"SYMoyaRxObjectMapper","symbolKind":"module","role":"collection","modules":[{"name":"SYMoyaRxObjectMapper"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Extended Modules","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper\/RxSwift"]}],"references":{"doc://com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper/documentation/SYMoyaRxObjectMapper":{"role":"collection","title":"SYMoyaRxObjectMapper","abstract":[{"type":"text","text":"Supports "},{"type":"codeVoice","code":"RxSwift"},{"type":"text","text":" responsive framework and uses "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":" to parse data."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper","kind":"symbol","type":"topic","url":"\/documentation\/symoyarxobjectmapper"},"doc://com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper/documentation/SYMoyaRxObjectMapper/SYMoyaRxObjectMapperVersionString":{"role":"symbol","title":"SYMoyaRxObjectMapperVersionString","fragments":[{"kind":"identifier","text":"SYMoyaRxObjectMapperVersionString"}],"abstract":[{"type":"text","text":"Project version string for SYMoyaRxObjectMapper."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper\/SYMoyaRxObjectMapperVersionString","kind":"symbol","type":"topic","url":"\/documentation\/symoyarxobjectmapper\/symoyarxobjectmapperversionstring"},"doc://com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper/documentation/SYMoyaRxObjectMapper/RxSwift":{"role":"collection","title":"RxSwift","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper\/RxSwift","kind":"symbol","type":"topic","url":"\/documentation\/symoyarxobjectmapper\/rxswift"},"doc://com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper/documentation/SYMoyaRxObjectMapper/SYMoyaRxObjectMapperVersionNumber":{"role":"symbol","title":"SYMoyaRxObjectMapperVersionNumber","fragments":[{"kind":"identifier","text":"SYMoyaRxObjectMapperVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for SYMoyaRxObjectMapper."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper\/SYMoyaRxObjectMapperVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/symoyarxobjectmapper\/symoyarxobjectmapperversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper\/SYMoyaRxObjectMapperVersionNumber","doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaRxObjectMapper\/documentation\/SYMoyaRxObjectMapper\/SYMoyaRxObjectMapperVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}