{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"earlyHints"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/go\/rfc8297"}]}],"type":"aside","name":"See Also"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/earlyhints"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/earlyhints"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/earlyHints","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Early Hints: 103"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"earlyHints"}],"title":"HTTPStatusCode.earlyHints","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SYMoyaNetwork@E@HTTPStatusCode@HTTPStatusCodeEarlyHints","modules":[{"name":"SYMoyaNetwork"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeEarlyHints"}]},"hierarchy":{"paths":[["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode"]]},"references":{"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode/earlyHints":{"role":"symbol","title":"HTTPStatusCode.earlyHints","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"earlyHints"}],"abstract":[{"type":"text","text":"Early Hints: 103"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/earlyHints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeEarlyHints"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode\/earlyhints"},"http://www.iana.org/go/rfc8297":{"title":"RFC8297","titleInlineContent":[{"type":"text","text":"RFC8297"}],"type":"link","identifier":"http:\/\/www.iana.org\/go\/rfc8297","url":"http:\/\/www.iana.org\/go\/rfc8297"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork":{"role":"collection","title":"SYMoyaNetwork","abstract":[{"type":"text","text":"Based on the network abstraction of secondary encapsulation of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":". Maintain the same usage method of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"TargetType"},{"type":"text","text":" implements commonly used data parsing, supporting: "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":","},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":", Developer there is no need to write boilerplate code for data parsing. You only need to care about what kind of data you want and select the data type. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has done all this. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" also implements network caching, and configure common caching strategies to only implement the desired caching strategy. "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" will perform cache synchronization according to the policy. Developers no longer need to spend a lot of time doing such work. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" allows data requests Become simple, less developers write boilerplate code, more time to focus on business."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeEarlyHints"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeEarlyHints"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeEarlyHints"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1earlyHints\/title","value":"HTTPStatusCodeEarlyHints"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1earlyHints\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeEarlyHints"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}