{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(HTTPStatusCodeIISLoginTimeout) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iisLoginTimeout"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The client’s session has expired and must log in again."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Category"}]},{"type":"text","text":": Internet Information Services"}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"http:\/\/support.microsoft.com\/kb\/941201\/en-us"}]}],"type":"aside","name":"See Also"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/iislogintimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/iislogintimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/iisLoginTimeout","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"IIS Login Timeout: 440"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iisLoginTimeout"}],"title":"HTTPStatusCode.iisLoginTimeout","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SYMoyaNetwork@E@HTTPStatusCode@HTTPStatusCodeIISLoginTimeout","modules":[{"name":"SYMoyaNetwork"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeIISLoginTimeout"}]},"hierarchy":{"paths":[["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode"]]},"references":{"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode/iisLoginTimeout":{"role":"symbol","title":"HTTPStatusCode.iisLoginTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iisLoginTimeout"}],"abstract":[{"type":"text","text":"IIS Login Timeout: 440"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/iisLoginTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeIISLoginTimeout"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode\/iislogintimeout"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork":{"role":"collection","title":"SYMoyaNetwork","abstract":[{"type":"text","text":"Based on the network abstraction of secondary encapsulation of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":". Maintain the same usage method of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"TargetType"},{"type":"text","text":" implements commonly used data parsing, supporting: "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":","},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":", Developer there is no need to write boilerplate code for data parsing. You only need to care about what kind of data you want and select the data type. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has done all this. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" also implements network caching, and configure common caching strategies to only implement the desired caching strategy. "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" will perform cache synchronization according to the policy. Developers no longer need to spend a lot of time doing such work. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" allows data requests Become simple, less developers write boilerplate code, more time to focus on business."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork"},"http://support.microsoft.com/kb/941201/en-us":{"title":"Error message when you try to log on to Exchange 2007 by using Outlook Web Access: “440 Login Timeout”","titleInlineContent":[{"type":"text","text":"Error message when you try to log on to Exchange 2007 by using Outlook Web Access: “440 Login Timeout”"}],"type":"link","identifier":"http:\/\/support.microsoft.com\/kb\/941201\/en-us","url":"http:\/\/support.microsoft.com\/kb\/941201\/en-us"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeIISLoginTimeout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeIISLoginTimeout"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeIISLoginTimeout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1iisLoginTimeout\/title","value":"HTTPStatusCodeIISLoginTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1iisLoginTimeout\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeIISLoginTimeout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}