{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returned by "},{"type":"reference","isActive":true,"identifier":"https:\/\/en.wikipedia.org\/wiki\/ArcGIS_Server"},{"type":"text","text":". A code of 498 indicates an expired or otherwise invalid token."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"http:\/\/help.arcgis.com\/en\/arcgisserver\/10.0\/apis\/soap\/index.htm#Using_token_authentication.htm"}]}],"type":"aside","name":"See Also"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/tokenexpired"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/tokenexpired"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/tokenExpired","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Token Expired: 498"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"title":"HTTPStatusCode.tokenExpired","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SYMoyaNetwork@E@HTTPStatusCode@HTTPStatusCodeTokenExpired","modules":[{"name":"SYMoyaNetwork"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeTokenExpired"}]},"hierarchy":{"paths":[["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode"]]},"references":{"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode/tokenExpired":{"role":"symbol","title":"HTTPStatusCode.tokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"abstract":[{"type":"text","text":"Token Expired: 498"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/tokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeTokenExpired"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode\/tokenexpired"},"http://help.arcgis.com/en/arcgisserver/10.0/apis/soap/index.htm#Using_token_authentication.htm":{"title":"Using token-based authentication","titleInlineContent":[{"type":"text","text":"Using token-based authentication"}],"type":"link","identifier":"http:\/\/help.arcgis.com\/en\/arcgisserver\/10.0\/apis\/soap\/index.htm#Using_token_authentication.htm","url":"http:\/\/help.arcgis.com\/en\/arcgisserver\/10.0\/apis\/soap\/index.htm#Using_token_authentication.htm"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"https://en.wikipedia.org/wiki/ArcGIS_Server":{"title":"ArcGIS for Server","titleInlineContent":[{"type":"text","text":"ArcGIS for Server"}],"type":"link","identifier":"https:\/\/en.wikipedia.org\/wiki\/ArcGIS_Server","url":"https:\/\/en.wikipedia.org\/wiki\/ArcGIS_Server"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork":{"role":"collection","title":"SYMoyaNetwork","abstract":[{"type":"text","text":"Based on the network abstraction of secondary encapsulation of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":". Maintain the same usage method of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"TargetType"},{"type":"text","text":" implements commonly used data parsing, supporting: "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":","},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":", Developer there is no need to write boilerplate code for data parsing. You only need to care about what kind of data you want and select the data type. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has done all this. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" also implements network caching, and configure common caching strategies to only implement the desired caching strategy. "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" will perform cache synchronization according to the policy. Developers no longer need to spend a lot of time doing such work. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" allows data requests Become simple, less developers write boilerplate code, more time to focus on business."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeTokenExpired"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeTokenExpired"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeTokenExpired"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1tokenExpired\/title","value":"HTTPStatusCodeTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1tokenExpired\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}