{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedMediaType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/go\/rfc7231#section-6.5.13"}]}],"type":"aside","name":"See Also"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/go\/rfc7694#section-3"}]}],"type":"aside","name":"See Also"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/unsupportedmediatype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/symoyanetwork\/httpstatuscode\/unsupportedmediatype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/unsupportedMediaType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unsupported Media Type: 415"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedMediaType"}],"title":"HTTPStatusCode.unsupportedMediaType","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SYMoyaNetwork@E@HTTPStatusCode@HTTPStatusCodeUnsupportedMediaType","modules":[{"name":"SYMoyaNetwork"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeUnsupportedMediaType"}]},"hierarchy":{"paths":[["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode"]]},"references":{"http://www.iana.org/go/rfc7231#section-6.5.13":{"title":"RFC7231, Section 6.5.13","titleInlineContent":[{"type":"text","text":"RFC7231, Section 6.5.13"}],"type":"link","identifier":"http:\/\/www.iana.org\/go\/rfc7231#section-6.5.13","url":"http:\/\/www.iana.org\/go\/rfc7231#section-6.5.13"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode/unsupportedMediaType":{"role":"symbol","title":"HTTPStatusCode.unsupportedMediaType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedMediaType"}],"abstract":[{"type":"text","text":"Unsupported Media Type: 415"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode\/unsupportedMediaType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeUnsupportedMediaType"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode\/unsupportedmediatype"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork":{"role":"collection","title":"SYMoyaNetwork","abstract":[{"type":"text","text":"Based on the network abstraction of secondary encapsulation of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":". Maintain the same usage method of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"TargetType"},{"type":"text","text":" implements commonly used data parsing, supporting: "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":","},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":", Developer there is no need to write boilerplate code for data parsing. You only need to care about what kind of data you want and select the data type. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has done all this. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" also implements network caching, and configure common caching strategies to only implement the desired caching strategy. "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" will perform cache synchronization according to the policy. Developers no longer need to spend a lot of time doing such work. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" allows data requests Become simple, less developers write boilerplate code, more time to focus on business."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode"},"http://www.iana.org/go/rfc7694#section-3":{"title":"RFC7694, Section 3","titleInlineContent":[{"type":"text","text":"RFC7694, Section 3"}],"type":"link","identifier":"http:\/\/www.iana.org\/go\/rfc7694#section-3","url":"http:\/\/www.iana.org\/go\/rfc7694#section-3"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeUnsupportedMediaType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeUnsupportedMediaType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeUnsupportedMediaType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1unsupportedMediaType\/title","value":"HTTPStatusCodeUnsupportedMediaType"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode~1unsupportedMediaType\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeUnsupportedMediaType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}