{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your project is using "},{"type":"codeVoice","code":"RXSwift"},{"type":"text","text":" as a responsive framework, which is a commonly used responsive framework in iOS development, then choosing to use the "},{"type":"codeVoice","code":"RxSYMoyaNetwork"},{"type":"text","text":" Framework is very suitable."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/rxsymoyanetwork"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/rxsymoyanetwork"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Support "},{"type":"codeVoice","code":"RXSwift"},{"type":"text","text":" responsive framework"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"RxSYMoyaNetwork","title":"RxSYMoyaNetwork","symbolKind":"module","role":"collection","modules":[{"name":"RxSYMoyaNetwork"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Extended Modules","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/RxSwift","doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/SYMoyaNetwork"]}],"references":{"doc://com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork/documentation/RxSYMoyaNetwork/SYMoyaNetwork":{"role":"collection","title":"SYMoyaNetwork","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/SYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/rxsymoyanetwork\/symoyanetwork"},"doc://com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork/documentation/RxSYMoyaNetwork/RxSYMoyaNetworkVersionNumber":{"role":"symbol","title":"RxSYMoyaNetworkVersionNumber","fragments":[{"kind":"identifier","text":"RxSYMoyaNetworkVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for RxSYMoyaNetwork."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/RxSYMoyaNetworkVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/rxsymoyanetwork\/rxsymoyanetworkversionnumber"},"doc://com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork/documentation/RxSYMoyaNetwork":{"role":"collection","title":"RxSYMoyaNetwork","abstract":[{"type":"text","text":"Support "},{"type":"codeVoice","code":"RXSwift"},{"type":"text","text":" responsive framework"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/rxsymoyanetwork"},"doc://com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork/documentation/RxSYMoyaNetwork/RxSYMoyaNetworkVersionString":{"role":"symbol","title":"RxSYMoyaNetworkVersionString","fragments":[{"kind":"identifier","text":"RxSYMoyaNetworkVersionString"}],"abstract":[{"type":"text","text":"Project version string for RxSYMoyaNetwork."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/RxSYMoyaNetworkVersionString","kind":"symbol","type":"topic","url":"\/documentation\/rxsymoyanetwork\/rxsymoyanetworkversionstring"},"doc://com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork/documentation/RxSYMoyaNetwork/RxSwift":{"role":"collection","title":"RxSwift","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/RxSwift","kind":"symbol","type":"topic","url":"\/documentation\/rxsymoyanetwork\/rxswift"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/RxSYMoyaNetworkVersionNumber","doc:\/\/com.shannonyang.SYMoyaNetwork.RxSYMoyaNetwork\/documentation\/RxSYMoyaNetwork\/RxSYMoyaNetworkVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}