{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your project is using "},{"type":"codeVoice","code":"Reactive"},{"type":"text","text":", and the data model parsing framework you use is "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", which is a commonly used responsive framework and data parsing framework in iOS development, then it is very suitable to use the "},{"type":"codeVoice","code":"SYMoyaReactiveObjectMapper"},{"type":"text","text":" Framework."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/symoyareactiveobjectmapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/symoyareactiveobjectmapper"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Supports "},{"type":"codeVoice","code":"Reactive"},{"type":"text","text":" responsive framework and uses "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":" to parse data."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SYMoyaReactiveObjectMapper","title":"SYMoyaReactiveObjectMapper","symbolKind":"module","role":"collection","modules":[{"name":"SYMoyaReactiveObjectMapper"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Extended Modules","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper\/ReactiveSwift"]}],"references":{"doc://com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper/documentation/SYMoyaReactiveObjectMapper/SYMoyaReactiveObjectMapperVersionString":{"role":"symbol","title":"SYMoyaReactiveObjectMapperVersionString","fragments":[{"kind":"identifier","text":"SYMoyaReactiveObjectMapperVersionString"}],"abstract":[{"type":"text","text":"Project version string for SYMoyaReactiveObjectMapper."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper\/SYMoyaReactiveObjectMapperVersionString","kind":"symbol","type":"topic","url":"\/documentation\/symoyareactiveobjectmapper\/symoyareactiveobjectmapperversionstring"},"doc://com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper/documentation/SYMoyaReactiveObjectMapper":{"role":"collection","title":"SYMoyaReactiveObjectMapper","abstract":[{"type":"text","text":"Supports "},{"type":"codeVoice","code":"Reactive"},{"type":"text","text":" responsive framework and uses "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":" to parse data."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper","kind":"symbol","type":"topic","url":"\/documentation\/symoyareactiveobjectmapper"},"doc://com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper/documentation/SYMoyaReactiveObjectMapper/ReactiveSwift":{"role":"collection","title":"ReactiveSwift","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper\/ReactiveSwift","kind":"symbol","type":"topic","url":"\/documentation\/symoyareactiveobjectmapper\/reactiveswift"},"doc://com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper/documentation/SYMoyaReactiveObjectMapper/SYMoyaReactiveObjectMapperVersionNumber":{"role":"symbol","title":"SYMoyaReactiveObjectMapperVersionNumber","fragments":[{"kind":"identifier","text":"SYMoyaReactiveObjectMapperVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for SYMoyaReactiveObjectMapper."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper\/SYMoyaReactiveObjectMapperVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/symoyareactiveobjectmapper\/symoyareactiveobjectmapperversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper\/SYMoyaReactiveObjectMapperVersionNumber","doc:\/\/com.shannonyang.SYMoyaNetwork.SYMoyaReactiveObjectMapper\/documentation\/SYMoyaReactiveObjectMapper\/SYMoyaReactiveObjectMapperVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}