{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Maybe you will use "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":" as an abstraction for network requests, like most iOS developers, "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":" is a great framework that standardizes your data requests and allows you to complete data requests simply enough. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" is based on "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":" secondary encapsulation, it does not change the way of using Moya, it is just a further expansion and more friendly encapsulation of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Maybe you would use Moya to write the request like this:"}]},{"type":"codeListing","syntax":"swift","code":["provider = MoyaProvider<GitHub>()","provider.request(.zen) { result in","    switch result {","    case let .success(moyaResponse):","        let data = moyaResponse.data","        let statusCode = moyaResponse.statusCode","        \/\/ do something with the response data or statusCode","    case let .failure(error):","        \/\/ this means there was a network failure - either the request","        \/\/ wasn't sent (connectivity), or no response was received (server","        \/\/ timed out).  If the server responds with a 4xx or 5xx error, that","        \/\/ will be sent as a \".success\"-ful response.","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the data request is completed, we need to manually convert "},{"type":"codeVoice","code":"moyaResponse"},{"type":"text","text":" into the data object we want. For example, when using "},{"type":"codeVoice","code":"ObjectMappe"},{"type":"text","text":" as the data model, we need to do it every time When returning a response, you need to convert "},{"type":"codeVoice","code":"moyaResponse"},{"type":"text","text":" into a "},{"type":"codeVoice","code":"BaseMappable"},{"type":"text","text":" object. Maybe you can encapsulate a unified method to do this, but you still need to manually call some of these conversion methods, which will make the user do this tediously. And tasteless work, so "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has done such a job, you only need to care about the data you want to get, "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" will give you the data you want to return, For example, when using "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":" as the data model, we can obtain the data object like this"}]},{"type":"codeListing","syntax":"swift","code":["provider = SYMoyaProvider<GitHub>()","\/\/\/ Note: `BaseMappable `here is the data type in which you implement `BaseMappable`, such as a `Class` or `Struct` or `Other` ","provider.responseObject(.zen) { (response: SYMoyaNetworkDataResponse<BaseMappable>) in","    switch response.result {","    case let .success(mappable):","        \/\/ The mappable will be the data you want to get, you can use it directly, you don’t need to do any conversion","    case let .failure(error):","        \/\/ this means there was a network failure - either the request","        \/\/ wasn't sent (connectivity), or no response was received (server","        \/\/ timed out).  If the server responds with a 4xx or 5xx error, that","        \/\/ will be sent as a \".success\"-ful response.","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Now using "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":", you no longer need to worry about how to convert the response into the data you want, you only need to care about the data you want, "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has already done all this."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" provides common data type parsing for a variety of data types, such as: "},{"type":"codeVoice","code":"JSON"},{"type":"text","text":", "},{"type":"codeVoice","code":"String"},{"type":"text","text":", "},{"type":"codeVoice","code":"Image"},{"type":"text","text":", "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":", "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":", when used You only need to care about the data you want to get, and you don’t need to care about the rest. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has already prepared the "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":" Analysis, you only care about your business implementation."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" not only converts the "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":", but more importantly, in "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":" "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has helped you with network caching. In most applications, network caching is very important. It can make your App display faster. Data can save data traffic for users. It can be said that it is a very important decision at the network layer. Therefore "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" provides the implementation of commonly used network caching strategies."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" supports "},{"type":"codeVoice","code":"Combine"},{"type":"text","text":", and also supports "},{"type":"codeVoice","code":"RxSwift"},{"type":"text","text":", "},{"type":"codeVoice","code":"ReactiveSwift"},{"type":"text","text":" and other commonly used responsive frameworks."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" also supports chain requests and batch requests. In most business situations, we may have a batch of requests to send, or related chain requests. also provides these Function can be implemented easily and quickly."}]},{"anchor":"Feature","level":2,"type":"heading","text":"Feature"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Support: "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":","},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":" data parsing, developers only need to care about the data you want to get."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Extend the "},{"type":"codeVoice","code":"TargetType"},{"type":"text","text":" of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":" and add "},{"type":"codeVoice","code":"timeoutInterval"},{"type":"text","text":", "},{"type":"codeVoice","code":"cdnURL"},{"type":"text","text":", "},{"type":"codeVoice","code":"allowsCellularAccess"},{"type":"text","text":", "},{"type":"codeVoice","code":"cachePolicy"},{"type":"text","text":" and other attributes."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Support data caching (disk and memory) and implement data caching strategies."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Support China Request."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Support Batch Request."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Supports "},{"type":"codeVoice","code":"Combine"},{"type":"text","text":", and also supports "},{"type":"codeVoice","code":"RxSwift"},{"type":"text","text":", "},{"type":"codeVoice","code":"ReactiveSwift"},{"type":"text","text":" and other commonly used responsive frameworks."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Supports "},{"type":"codeVoice","code":"Concurrency"},{"type":"text","text":" asynchronous calls."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Supports request log output, and request data information is clear at a glance."}]}]}]},{"anchor":"Tip","level":2,"type":"heading","text":"Tip"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" In order to support different types of data parsing, different types of data parsing are split into different Framework packages. All parsing data packages depend on the core "},{"type":"codeVoice","code":"Core"},{"type":"text","text":" package. Developers can choose the parsing to use. Type to install, for example: use "},{"type":"codeVoice","code":"RxSwift"},{"type":"text","text":" to directly install the "},{"type":"codeVoice","code":"SYMoyaObjectMapper"},{"type":"text","text":" package, if you also need to use "},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":" as data parsing, then you can install "},{"type":"codeVoice","code":"SYMoyaRxObjectMapper"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"SYMoyaNetwork"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/symoyanetwork"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/symoyanetwork"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Based on the network abstraction of secondary encapsulation of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":". Maintain the same usage method of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"TargetType"},{"type":"text","text":" implements commonly used data parsing, supporting: "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":","},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":", Developer there is no need to write boilerplate code for data parsing. You only need to care about what kind of data you want and select the data type. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has done all this. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" also implements network caching, and configure common caching strategies to only implement the desired caching strategy. "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" will perform cache synchronization according to the policy. Developers no longer need to spend a lot of time doing such work. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" allows data requests Become simple, less developers write boilerplate code, more time to focus on business."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SYMoyaNetwork","title":"SYMoyaNetwork","symbolKind":"module","role":"collection","modules":[{"name":"SYMoyaNetwork"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"SYMoya","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProvider","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderSessionResponse","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderRequestable","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ResponseSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ResponseDataSourceType","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYTargetType","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkResult"]},{"title":"Batch Request","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaBatchProviderSession","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYBatchProgress","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaBatchProvider","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaBatchProviderReqOperation","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYBatchMoyaProviderType","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYBatchProgressBlock"]},{"title":"Chain Request","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYChainMoyaProviderType","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaChainProvider","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaChainProviderSession"]},{"title":"Response","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DecodableResponseSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SwiftyJSONResponseSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/StringResponseSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/JSONResponseSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ImageResponseSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYDataResponse","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYDataResponseActor"]},{"title":"Utility","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaPublisher","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/AsyncOperation","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CallbackQueue","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPHeaders","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPVersion"]},{"title":"Plugin","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkLoggerPlugin","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderTargetResponseStatePlugin"]},{"title":"Error","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkError"]},{"title":"Cache","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/StorageExpiration","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DiskStorage","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/MemoryStorage","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCache","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkOptionsInfo","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCacheType","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCacheFromType"]},{"title":"Config","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkConfig"]},{"title":"Classes","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderTargetResponseStateItem"]},{"title":"Protocols","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheCostCalculable","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DataTransformable","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ResponseDataSourceCustomizable","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderDelegate"]},{"title":"Structures","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheStoreResult","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DefaultCacheSerializer","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkParsedOptionsInfo"]},{"title":"Variables","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkDiskCacheCleanedHashKey"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ExecutionQueue","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/LogConfiguration","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkDataResponse","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkResultResponse"]},{"title":"Enumerations","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheType","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ExpirationExtending","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCacheResult","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkOptionsInfoItem","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderResponseState"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/Foundation","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/Moya","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/Swift"]}],"references":{"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaProviderDelegate":{"role":"symbol","title":"SYMoyaProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaProviderDelegate"}],"abstract":[{"type":"text","text":"The provider proxy method is called back. When the completion method of moya is called back, the corresponding proxy method will be called back."},{"type":"text","text":" "},{"type":"text","text":"When the network request is completed, the requestCompleteFilter method will be called back. When the request fails, the requestFailedFilter method will be called back."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaProviderDelegate"}],"url":"\/documentation\/symoyanetwork\/symoyaproviderdelegate"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/NetworkCacheType":{"role":"symbol","title":"NetworkCacheType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkCacheType"}],"abstract":[{"type":"text","text":"Network Cache type of a cached Request."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkCacheType"}],"url":"\/documentation\/symoyanetwork\/networkcachetype"},"SYMoyaNetwork":{"alt":"SYMoyaNetwork","type":"image","identifier":"SYMoyaNetwork","variants":[{"url":"\/images\/SYMoyaNetwork.png","traits":["1x","light"]}]},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkVersionNumber":{"role":"symbol","title":"SYMoyaNetworkVersionNumber","fragments":[{"kind":"identifier","text":"SYMoyaNetworkVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for SYMoyaNetwork."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork\/symoyanetworkversionnumber"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYDataResponseActor":{"role":"symbol","title":"SYDataResponseActor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYDataResponseActor"}],"abstract":[{"type":"text","text":"An actor wrapping SYMoyaProvider"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYDataResponseActor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYDataResponseActor"}],"url":"\/documentation\/symoyanetwork\/sydataresponseactor"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaBatchProvider":{"role":"symbol","title":"SYMoyaBatchProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaBatchProvider"}],"abstract":[{"type":"text","text":"Batch Request provider class. Batch Requests should be made through this class only."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaBatchProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaBatchProvider"}],"url":"\/documentation\/symoyanetwork\/symoyabatchprovider"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/JSONResponseSerializer":{"role":"symbol","title":"JSONResponseSerializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONResponseSerializer"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ResponseSerializer"},{"type":"text","text":" that decodes the response data as a "},{"type":"codeVoice","code":"JSON"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/JSONResponseSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONResponseSerializer"}],"url":"\/documentation\/symoyanetwork\/jsonresponseserializer"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkParsedOptionsInfo":{"role":"symbol","title":"SYMoyaNetworkParsedOptionsInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkParsedOptionsInfo"}],"abstract":[{"type":"text","text":"The parsed options info used across SYMoyaNetwork methods. Each property in this type corresponds a case member"},{"type":"text","text":" "},{"type":"text","text":"in "},{"type":"codeVoice","code":"SYMoyaNetworkOptionsInfoItem"},{"type":"text","text":". When a "},{"type":"codeVoice","code":"SYMoyaNetworkOptionsInfo"},{"type":"text","text":" sent to SYMoyaNetwork related methods, it will be"},{"type":"text","text":" "},{"type":"text","text":"parsed and converted to a "},{"type":"codeVoice","code":"SYMoyaNetworkParsedOptionsInfo"},{"type":"text","text":" first, and pass through the internal methods."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkParsedOptionsInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkParsedOptionsInfo"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkparsedoptionsinfo"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkVersionString":{"role":"symbol","title":"SYMoyaNetworkVersionString","fragments":[{"kind":"identifier","text":"SYMoyaNetworkVersionString"}],"abstract":[{"type":"text","text":"Project version string for SYMoyaNetwork."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkVersionString","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork\/symoyanetworkversionstring"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/StorageExpiration":{"role":"symbol","title":"StorageExpiration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StorageExpiration"}],"abstract":[{"type":"text","text":"Represents the expiration strategy used in storage."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/StorageExpiration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StorageExpiration"}],"url":"\/documentation\/symoyanetwork\/storageexpiration"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/NetworkCacheFromType":{"role":"symbol","title":"NetworkCacheFromType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkCacheFromType"}],"abstract":[{"type":"text","text":"Network cache retrieval type."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCacheFromType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkCacheFromType"}],"url":"\/documentation\/symoyanetwork\/networkcachefromtype"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/Foundation":{"role":"collection","title":"Foundation","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/Foundation","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork\/foundation"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/DiskStorage":{"role":"symbol","title":"DiskStorage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiskStorage"}],"abstract":[{"type":"text","text":"Represents a set of conception related to storage which stores a certain type of value in disk."},{"type":"text","text":" "},{"type":"text","text":"This is a namespace for the disk storage types. A "},{"type":"codeVoice","code":"Backend"},{"type":"text","text":" with a certain "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" will be used to describe the"},{"type":"text","text":" "},{"type":"text","text":"storage. See these composed types for more information."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DiskStorage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiskStorage"}],"url":"\/documentation\/symoyanetwork\/diskstorage"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SwiftyJSONResponseSerializer":{"role":"symbol","title":"SwiftyJSONResponseSerializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftyJSONResponseSerializer"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ResponseSerializer"},{"type":"text","text":" that decodes the response data as a "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SwiftyJSONResponseSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwiftyJSONResponseSerializer"}],"url":"\/documentation\/symoyanetwork\/swiftyjsonresponseserializer"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/Moya":{"role":"collection","title":"Moya","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/Moya","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork\/moya"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkResultResponse":{"role":"symbol","title":"SYMoyaNetworkResultResponse","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkResultResponse"}],"abstract":[{"type":"text","text":"Data request response object, "},{"type":"codeVoice","code":"isDataFromCache"},{"type":"text","text":" indicates whether the currently retrieved data comes from the cache"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkResultResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkResultResponse"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkresultresponse"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/ResponseDataSourceCustomizable":{"role":"symbol","title":"ResponseDataSourceCustomizable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseDataSourceCustomizable"}],"abstract":[{"type":"text","text":"CacheCustomizable protocol"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ResponseDataSourceCustomizable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseDataSourceCustomizable"}],"url":"\/documentation\/symoyanetwork\/responsedatasourcecustomizable"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYTargetType":{"role":"symbol","title":"SYTargetType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYTargetType"}],"abstract":[{"type":"text","text":"The protocol used to define the specifications necessary for a "},{"type":"codeVoice","code":"SYMoyaProvider"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Inherit Moya.TargetType, extend more properties that can be set for TargetType, and add network cache type settings"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYTargetType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYTargetType"}],"url":"\/documentation\/symoyanetwork\/sytargettype"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/ResponseDataSourceType":{"role":"symbol","title":"ResponseDataSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseDataSourceType"}],"abstract":[{"type":"text","text":"Request’s responseData source type, implementing different type responseData source type"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ResponseDataSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseDataSourceType"}],"url":"\/documentation\/symoyanetwork\/responsedatasourcetype"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkLoggerPlugin":{"role":"symbol","title":"SYMoyaNetworkLoggerPlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkLoggerPlugin"}],"abstract":[{"type":"text","text":"Network request log print plugin object"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkLoggerPlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkLoggerPlugin"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkloggerplugin"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPHeaders":{"role":"symbol","title":"HTTPHeaders","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPHeaders"}],"abstract":[{"type":"text","text":"Representation of the HTTP headers associated with a "},{"type":"codeVoice","code":"HTTPRequest"},{"type":"text","text":" or "},{"type":"codeVoice","code":"HTTPResponse"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Headers are subscriptable using case-insensitive comparison or provide "},{"type":"codeVoice","code":"Name"},{"type":"text","text":" constants. eg."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPHeaders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPHeaders"}],"url":"\/documentation\/symoyanetwork\/httpheaders"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/ExpirationExtending":{"role":"symbol","title":"ExpirationExtending","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpirationExtending"}],"abstract":[{"type":"text","text":"Represents the expiration extending strategy used in storage to after access."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ExpirationExtending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExpirationExtending"}],"url":"\/documentation\/symoyanetwork\/expirationextending"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/NetworkConfig":{"role":"symbol","title":"NetworkConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConfig"}],"abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkConfig"}],"url":"\/documentation\/symoyanetwork\/networkconfig"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPVersion":{"role":"symbol","title":"HTTPVersion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPVersion"}],"abstract":[{"type":"text","text":"Version number of the HTTP Protocol"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPVersion"}],"url":"\/documentation\/symoyanetwork\/httpversion"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYBatchProgressBlock":{"role":"symbol","title":"SYBatchProgressBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYBatchProgressBlock"}],"abstract":[{"type":"text","text":"Closure to be executed when progress changes."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYBatchProgressBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYBatchProgressBlock"}],"url":"\/documentation\/symoyanetwork\/sybatchprogressblock"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkOptionsInfoItem":{"role":"symbol","title":"SYMoyaNetworkOptionsInfoItem","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkOptionsInfoItem"}],"abstract":[{"type":"text","text":"Represents the available option items could be used in "},{"type":"codeVoice","code":"SYMoyaNetworkOptionsInfo"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkOptionsInfoItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkOptionsInfoItem"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkoptionsinfoitem"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/NetworkCacheResult":{"role":"symbol","title":"NetworkCacheResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkCacheResult"}],"abstract":[{"type":"text","text":"Represents the getting Response operation from the cache."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCacheResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkCacheResult"}],"url":"\/documentation\/symoyanetwork\/networkcacheresult"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaProviderTargetResponseStatePlugin":{"role":"symbol","title":"SYMoyaProviderTargetResponseStatePlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaProviderTargetResponseStatePlugin"}],"abstract":[{"type":"text","text":"SYMoyaProvider request state plugin"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderTargetResponseStatePlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaProviderTargetResponseStatePlugin"}],"url":"\/documentation\/symoyanetwork\/symoyaprovidertargetresponsestateplugin"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaBatchProviderReqOperation":{"role":"symbol","title":"SYMoyaBatchProviderReqOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaBatchProviderReqOperation"}],"abstract":[{"type":"text","text":"Inherit "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/AsyncOperation"},{"type":"text","text":" and implement specific tasks for Batch request objects."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaBatchProviderReqOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaBatchProviderReqOperation"}],"url":"\/documentation\/symoyanetwork\/symoyabatchproviderreqoperation"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/CacheSerializer":{"role":"symbol","title":"CacheSerializer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheSerializer"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"CacheSerializer"},{"type":"text","text":" is used to convert some data to an response object after"},{"type":"text","text":" "},{"type":"text","text":"retrieving it from disk storage, and vice versa, to convert an response to data object"},{"type":"text","text":" "},{"type":"text","text":"for storing to the disk storage."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheSerializer"}],"url":"\/documentation\/symoyanetwork\/cacheserializer"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/NetworkCache":{"role":"symbol","title":"NetworkCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkCache"}],"abstract":[{"type":"text","text":"Represents a hybrid caching system which is composed by a "},{"type":"codeVoice","code":"MemoryStorage.Backend"},{"type":"text","text":" and a "},{"type":"codeVoice","code":"DiskStorage.Backend"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"NetworkCache"},{"type":"text","text":" is a high level abstract for storing an Moya.Response as well as its data to disk memory and disk, and"},{"type":"text","text":" "},{"type":"text","text":"retrieving them back."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/NetworkCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkCache"}],"url":"\/documentation\/symoyanetwork\/networkcache"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkDataResponse":{"role":"symbol","title":"SYMoyaNetworkDataResponse","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkDataResponse"}],"abstract":[{"type":"text","text":"An object specifically referring to "},{"type":"codeVoice","code":"SYDataResponse"},{"type":"text","text":" whose failure value is "},{"type":"codeVoice","code":"SYMoyaNetworkError"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkDataResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkDataResponse"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkdataresponse"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaProviderSessionResponse":{"role":"symbol","title":"SYMoyaProviderSessionResponse","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaProviderSessionResponse"}],"abstract":[{"type":"text","text":"Response wrapper object for "},{"type":"codeVoice","code":"SYMoyaBatchProviderSession"},{"type":"text","text":" and "},{"type":"codeVoice","code":"SYMoyaChainProviderSession"},{"type":"text","text":", used for responses to batch and chain requests"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderSessionResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaProviderSessionResponse"}],"url":"\/documentation\/symoyanetwork\/symoyaprovidersessionresponse"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/ExecutionQueue":{"role":"symbol","title":"ExecutionQueue","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExecutionQueue"}],"abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ExecutionQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExecutionQueue"}],"url":"\/documentation\/symoyanetwork\/executionqueue"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/symoyanetwork\/httpstatuscode"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYChainMoyaProviderType":{"role":"symbol","title":"SYChainMoyaProviderType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYChainMoyaProviderType"}],"abstract":[{"type":"text","text":"Chain request abstract protocol"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYChainMoyaProviderType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYChainMoyaProviderType"}],"url":"\/documentation\/symoyanetwork\/sychainmoyaprovidertype"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/CacheCostCalculable":{"role":"symbol","title":"CacheCostCalculable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheCostCalculable"}],"abstract":[{"type":"text","text":"Represents types which cost in memory can be calculated."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheCostCalculable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheCostCalculable"}],"url":"\/documentation\/symoyanetwork\/cachecostcalculable"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkError":{"role":"symbol","title":"SYMoyaNetworkError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkError"}],"abstract":[{"type":"text","text":"Represents all the errors which can happen in SYMoyaNetwork framework."},{"type":"text","text":" "},{"type":"text","text":"SYMoyaNetwork related methods always throw a "},{"type":"codeVoice","code":"SYMoyaNetworkError"},{"type":"text","text":" or invoke the callback with "},{"type":"codeVoice","code":"SYMoyaNetworkError"},{"type":"text","text":" "},{"type":"text","text":"as its error type. To handle errors from SYMoyaNetwork, you switch over the error to get a reason catalog,"},{"type":"text","text":" "},{"type":"text","text":"then switch over the reason to know error detail."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkError"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkerror"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/Swift":{"role":"collection","title":"Swift","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/Swift","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork\/swift"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/CacheType":{"role":"symbol","title":"CacheType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheType"}],"abstract":[{"type":"text","text":"Cache type of a cached Response."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheType"}],"url":"\/documentation\/symoyanetwork\/cachetype"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaPublisher":{"role":"symbol","title":"SYMoyaPublisher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaPublisher"}],"abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaPublisher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaPublisher"}],"url":"\/documentation\/symoyanetwork\/symoyapublisher"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaProvider":{"role":"symbol","title":"SYMoyaProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaProvider"}],"abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaProvider"}],"url":"\/documentation\/symoyanetwork\/symoyaprovider"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYDataResponse":{"role":"symbol","title":"SYDataResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYDataResponse"}],"abstract":[{"type":"text","text":"Represents a response to a "},{"type":"codeVoice","code":"SYMoyaProvider.request"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYDataResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYDataResponse"}],"url":"\/documentation\/symoyanetwork\/sydataresponse"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaProviderTargetResponseStateItem":{"role":"symbol","title":"SYMoyaProviderTargetResponseStateItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaProviderTargetResponseStateItem"}],"abstract":[{"type":"text","text":"A request state object holding TargetType"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderTargetResponseStateItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaProviderTargetResponseStateItem"}],"url":"\/documentation\/symoyanetwork\/symoyaprovidertargetresponsestateitem"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/ResponseSerializer":{"role":"symbol","title":"ResponseSerializer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseSerializer"}],"abstract":[{"type":"text","text":"Data serializer abstract protocol, Serializer "},{"type":"codeVoice","code":"SYMoyaNetworkResult"},{"type":"text","text":" to "},{"type":"codeVoice","code":"SYMoyaNetworkDataResponse"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ResponseSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseSerializer"}],"url":"\/documentation\/symoyanetwork\/responseserializer"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/StringResponseSerializer":{"role":"symbol","title":"StringResponseSerializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StringResponseSerializer"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ResponseSerializer"},{"type":"text","text":" that decodes the response data as a "},{"type":"codeVoice","code":"String"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/StringResponseSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StringResponseSerializer"}],"url":"\/documentation\/symoyanetwork\/stringresponseserializer"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkOptionsInfo":{"role":"symbol","title":"SYMoyaNetworkOptionsInfo","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkOptionsInfo"}],"abstract":[{"type":"text","text":"SYMoyaNetworkOptionsInfo is a typealias for [SYMoyaNetworkOptionsInfoItem]."},{"type":"text","text":" "},{"type":"text","text":"You can use the enum of option item with value to control some behaviors of SYMoyaNetwork."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkOptionsInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkOptionsInfo"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkoptionsinfo"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/LogConfiguration":{"role":"symbol","title":"LogConfiguration","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogConfiguration"}],"abstract":[{"type":"text","text":"Default Log Configuation"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/LogConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogConfiguration"}],"url":"\/documentation\/symoyanetwork\/logconfiguration"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/CallbackQueue":{"role":"symbol","title":"CallbackQueue","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallbackQueue"}],"abstract":[{"type":"text","text":"Represents callback queue behaviors when an calling of closure be dispatched."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CallbackQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallbackQueue"}],"url":"\/documentation\/symoyanetwork\/callbackqueue"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/ImageResponseSerializer":{"role":"symbol","title":"ImageResponseSerializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageResponseSerializer"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ResponseSerializer"},{"type":"text","text":" that decodes the response data as a "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/ImageResponseSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageResponseSerializer"}],"url":"\/documentation\/symoyanetwork\/imageresponseserializer"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaChainProviderSession":{"role":"symbol","title":"SYMoyaChainProviderSession","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaChainProviderSession"}],"abstract":[{"type":"text","text":"The chained request provider is used to manage interdependent network requests, and it can actually eventually be used to manage multiple topologically sorted network requests."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaChainProviderSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaChainProviderSession"}],"url":"\/documentation\/symoyanetwork\/symoyachainprovidersession"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaProviderRequestable":{"role":"symbol","title":"SYMoyaProviderRequestable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaProviderRequestable"}],"abstract":[{"type":"text","text":"An abstraction layer that defines the common request method of Provider."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderRequestable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaProviderRequestable"}],"url":"\/documentation\/symoyanetwork\/symoyaproviderrequestable"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/DataTransformable":{"role":"symbol","title":"DataTransformable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataTransformable"}],"abstract":[{"type":"text","text":"Represents types which can be converted to and from data."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DataTransformable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DataTransformable"}],"url":"\/documentation\/symoyanetwork\/datatransformable"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYBatchProgress":{"role":"symbol","title":"SYBatchProgress","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYBatchProgress"}],"abstract":[{"type":"text","text":"An object describing the progress of a batch request"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYBatchProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYBatchProgress"}],"url":"\/documentation\/symoyanetwork\/sybatchprogress"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYBatchMoyaProviderType":{"role":"symbol","title":"SYBatchMoyaProviderType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYBatchMoyaProviderType"}],"abstract":[{"type":"text","text":"Batch request abstract protocol"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYBatchMoyaProviderType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYBatchMoyaProviderType"}],"url":"\/documentation\/symoyanetwork\/sybatchmoyaprovidertype"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/AsyncOperation":{"role":"symbol","title":"AsyncOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncOperation"}],"abstract":[{"type":"text","text":"An asynchronous operation object that implements "},{"type":"codeVoice","code":"Operation"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/AsyncOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AsyncOperation"}],"url":"\/documentation\/symoyanetwork\/asyncoperation"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork":{"role":"collection","title":"SYMoyaNetwork","abstract":[{"type":"text","text":"Based on the network abstraction of secondary encapsulation of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":". Maintain the same usage method of "},{"type":"codeVoice","code":"Moya"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"TargetType"},{"type":"text","text":" implements commonly used data parsing, supporting: "},{"type":"codeVoice","code":"HandyJSON"},{"type":"text","text":","},{"type":"codeVoice","code":"ObjectMapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftyJSON"},{"type":"text","text":", Developer there is no need to write boilerplate code for data parsing. You only need to care about what kind of data you want and select the data type. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" has done all this. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" also implements network caching, and configure common caching strategies to only implement the desired caching strategy. "},{"type":"codeVoice","code":"Response"},{"type":"text","text":" will perform cache synchronization according to the policy. Developers no longer need to spend a lot of time doing such work. "},{"type":"codeVoice","code":"SYMoyaNetwork"},{"type":"text","text":" allows data requests Become simple, less developers write boilerplate code, more time to focus on business."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaProviderResponseState":{"role":"symbol","title":"SYMoyaProviderResponseState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaProviderResponseState"}],"abstract":[{"type":"text","text":"The provider request response status, the status change from the initiation to the end of the network request"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaProviderResponseState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaProviderResponseState"}],"url":"\/documentation\/symoyanetwork\/symoyaproviderresponsestate"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/DefaultCacheSerializer":{"role":"symbol","title":"DefaultCacheSerializer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCacheSerializer"}],"abstract":[{"type":"text","text":"Represents a basic and default "},{"type":"codeVoice","code":"CacheSerializer"},{"type":"text","text":" used in SYMoyaNetwork disk cache system."},{"type":"text","text":" "},{"type":"text","text":"It could serialize and deserialize response For"},{"type":"text","text":" "},{"type":"text","text":"response other than these formats, a normalized "},{"type":"codeVoice","code":"pngRepresentation"},{"type":"text","text":" will be used."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DefaultCacheSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultCacheSerializer"}],"url":"\/documentation\/symoyanetwork\/defaultcacheserializer"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkResult":{"role":"symbol","title":"SYMoyaNetworkResult","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkResult"}],"abstract":[{"type":"text","text":"A data request result object with "},{"type":"codeVoice","code":"SYMoyaNetworkResultResponse"},{"type":"text","text":" and "},{"type":"codeVoice","code":"SYMoyaNetworkError"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaNetworkResult"}],"url":"\/documentation\/symoyanetwork\/symoyanetworkresult"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/MemoryStorage":{"role":"symbol","title":"MemoryStorage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemoryStorage"}],"abstract":[{"type":"text","text":"Represents a set of conception related to storage which stores a certain type of value in memory."},{"type":"text","text":" "},{"type":"text","text":"This is a namespace for the memory storage types. A "},{"type":"codeVoice","code":"Backend"},{"type":"text","text":" with a certain "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" will be used to describe the"},{"type":"text","text":" "},{"type":"text","text":"storage. See these composed types for more information."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/MemoryStorage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemoryStorage"}],"url":"\/documentation\/symoyanetwork\/memorystorage"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaNetworkDiskCacheCleanedHashKey":{"role":"symbol","title":"SYMoyaNetworkDiskCacheCleanedHashKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaNetworkDiskCacheCleanedHashKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Key for array of cleaned hashes in "},{"type":"codeVoice","code":"userInfo"},{"type":"text","text":" of "},{"type":"codeVoice","code":"SYMoyaNetworkDidCleanDiskCacheNotification"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkDiskCacheCleanedHashKey","kind":"symbol","type":"topic","url":"\/documentation\/symoyanetwork\/symoyanetworkdiskcachecleanedhashkey"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/CacheStoreResult":{"role":"symbol","title":"CacheStoreResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheStoreResult"}],"abstract":[{"type":"text","text":"Represents the caching operation result."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/CacheStoreResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheStoreResult"}],"url":"\/documentation\/symoyanetwork\/cachestoreresult"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaChainProvider":{"role":"symbol","title":"SYMoyaChainProvider","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaChainProvider"}],"abstract":[{"type":"text","text":"Chain Request provider class. Chain Requests should be made through this class only."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaChainProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaChainProvider"}],"url":"\/documentation\/symoyanetwork\/symoyachainprovider"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/SYMoyaBatchProviderSession":{"role":"symbol","title":"SYMoyaBatchProviderSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SYMoyaBatchProviderSession"}],"abstract":[{"type":"text","text":"Batch request session object, used to session the sending and callback of batch requests"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaBatchProviderSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SYMoyaBatchProviderSession"}],"url":"\/documentation\/symoyanetwork\/symoyabatchprovidersession"},"doc://com.shannonyang.SYMoyaNetwork/documentation/SYMoyaNetwork/DecodableResponseSerializer":{"role":"symbol","title":"DecodableResponseSerializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DecodableResponseSerializer"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ResponseSerializer"},{"type":"text","text":" that decodes the response data as a "},{"type":"codeVoice","code":"Decodable"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/DecodableResponseSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DecodableResponseSerializer"}],"url":"\/documentation\/symoyanetwork\/decodableresponseserializer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Utility","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/AsyncOperation","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/HTTPStatusCode"]},{"title":"Variables","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkVersionNumber","doc:\/\/com.shannonyang.SYMoyaNetwork\/documentation\/SYMoyaNetwork\/SYMoyaNetworkVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1AsyncOperation\/title","value":"AsyncOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.shannonyang.SYMoyaNetwork~1documentation~1SYMoyaNetwork~1AsyncOperation\/fragments","value":[{"kind":"identifier","text":"AsyncOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}