{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your project is using "},{"type":"codeVoice","code":"Reactive"},{"type":"text","text":" as a responsive framework, which is a commonly used responsive framework in iOS development, then choosing to use the "},{"type":"codeVoice","code":"ReactiveSYMoyaNetwork"},{"type":"text","text":" Framework is very suitable."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/reactivesymoyanetwork"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/reactivesymoyanetwork"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Support "},{"type":"codeVoice","code":"Reactive"},{"type":"text","text":" responsive framework"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"ReactiveSYMoyaNetwork","title":"ReactiveSYMoyaNetwork","symbolKind":"module","role":"collection","modules":[{"name":"ReactiveSYMoyaNetwork"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Extended Modules","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/ReactiveSwift","doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/SYMoyaNetwork"]}],"references":{"doc://com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork/documentation/ReactiveSYMoyaNetwork/ReactiveSwift":{"role":"collection","title":"ReactiveSwift","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/ReactiveSwift","kind":"symbol","type":"topic","url":"\/documentation\/reactivesymoyanetwork\/reactiveswift"},"doc://com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork/documentation/ReactiveSYMoyaNetwork":{"role":"collection","title":"ReactiveSYMoyaNetwork","abstract":[{"type":"text","text":"Support "},{"type":"codeVoice","code":"Reactive"},{"type":"text","text":" responsive framework"}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/reactivesymoyanetwork"},"doc://com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork/documentation/ReactiveSYMoyaNetwork/ReactiveSYMoyaNetworkVersionString":{"role":"symbol","title":"ReactiveSYMoyaNetworkVersionString","fragments":[{"kind":"identifier","text":"ReactiveSYMoyaNetworkVersionString"}],"abstract":[{"type":"text","text":"Project version string for ReactiveSYMoyaNetwork."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/ReactiveSYMoyaNetworkVersionString","kind":"symbol","type":"topic","url":"\/documentation\/reactivesymoyanetwork\/reactivesymoyanetworkversionstring"},"doc://com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork/documentation/ReactiveSYMoyaNetwork/SYMoyaNetwork":{"role":"collection","title":"SYMoyaNetwork","abstract":[],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/SYMoyaNetwork","kind":"symbol","type":"topic","url":"\/documentation\/reactivesymoyanetwork\/symoyanetwork"},"doc://com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork/documentation/ReactiveSYMoyaNetwork/ReactiveSYMoyaNetworkVersionNumber":{"role":"symbol","title":"ReactiveSYMoyaNetworkVersionNumber","fragments":[{"kind":"identifier","text":"ReactiveSYMoyaNetworkVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for ReactiveSYMoyaNetwork."}],"identifier":"doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/ReactiveSYMoyaNetworkVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/reactivesymoyanetwork\/reactivesymoyanetworkversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/ReactiveSYMoyaNetworkVersionNumber","doc:\/\/com.shannonyang.SYMoyaNetwork.ReactiveSYMoyaNetwork\/documentation\/ReactiveSYMoyaNetwork\/ReactiveSYMoyaNetworkVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}